ASRP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('timetable.urls')),
    url(r'^operator/', include('operatorroom.urls')),
    url(r'^expert/', include('expertroom.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

timetable/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager
from tools.string import GenerateString as GS
from django.core.mail import EmailMultiAlternatives
from tools import smsc_api
from django.conf import settings
from tools.url import getUrl
import datetime
from django.views.generic.list import ListView
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class Organization(models.Model):
	organization_name = models.CharField(max_length=100)
	organization_logo = models.ImageField(upload_to='logos',default=None)

	def __str__(self):
		return self.organization_name
	class Meta:
		verbose_name = 'Организация'
		verbose_name_plural = 'Организации'
		
class City(models.Model):
	city_name = models.CharField(max_length=30)
	def __str__(self):
		return self.city_name	
	class Meta:
		verbose_name = 'Город'
		verbose_name_plural = 'Города'

class Filial(models.Model):
	filial_name = models.CharField(max_length=100)
	filial_organization = models.ForeignKey('Organization')
	filial_city = models.ForeignKey('City')
	filial_street = models.CharField(max_length=50,default="")
	filial_house = models.CharField(max_length=50,default="")
	def __str__(self):
		return self.filial_name
	class Meta:
		verbose_name = 'Отделение'
		verbose_name_plural = 'Отделения'

class Speciality(models.Model):
	speciality_name = models.CharField(max_length=50)
	def __str__(self):
		return self.speciality_name
	class Meta:
		verbose_name = 'Специальность'
		verbose_name_plural = 'Специальности'

class Client(User):
	client_phone = models.CharField(max_length=15)
	client_patronymic = models.CharField(max_length=30, default="")
	client_code_email = models.CharField(max_length=15, default="")
	client_code_phone = models.CharField(max_length=5, default="")
	client_confirm_email = models.BooleanField(default=False)
	client_confirm_phone = models.BooleanField(default=False)

	objects = UserManager()
	def set_email(self, sEmail):
		try:
			Client.objects.get(email=sEmail)
			return False
		except:
			self.email = sEmail
			self.client_confirm_email = False
			self.save()
			self.send_confirm_email()
			return True

	@property
	def full_name(self):
		if not hasattr(self, '_full_name'):
			self._full_name = self.last_name + " " + self.first_name + " " + self.client_patronymic
		return self._full_name


	
	def check_phone(self, cPhone):
		try:
			Client.objects.get(client_phone=cPhone)
			return True
		except:
			return False

	def check_email(email):
		try:
			Client.objects.get(email=email)
			return False
		except:
			try:
				validate_email(email)
			except ValidationError as e:
				return False
			return True

	def check_username(username):
		try:
			Client.objects.get(username=username)
			return False
		except:
			return True

	def set_new_phone(self,sPhone):
		#need some IFes
		self.client_phone = '7' + sPhone
		self.client_confirm_phone = False
		self.save()
		self.send_confirm_phone()


	def set_code_email(self):
		self.client_code_email = GS(15)
		self.save()
		return self.client_code_email

	def set_code_phone(self):
		self.client_code_phone = GS(5)
		self.save()
		return self.client_code_phone

	def generate_password(self, count):
		passw = GS(5)
		self.set_password(passw)
		if self.client_confirm_phone:
			self.send_sms("Ваш пароль для доступа в систему: " +passw)
		self.send_mail("Ваш пароль для доступа в систему: " +passw)
		return passw

	def send_confirm_email(self):
		self.set_code_email()		
		subject, from_email, to = 'Подтверждение регистрации', 'ruka2paka@yandex.ru', self.email
		text_content = 'This is an important message.'
		html_content = '<p>Ваша ссылка для подтверждения: <a href="http://127.0.0.1:8000' + getUrl('timetable_confirm',username=self.username,tpl="email",code=self.client_code_email) + '">нажмите для подтверждения</a> </p>'
		msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

	def send_confirm_phone(self):
		print (self.set_code_phone())
		smsc = smsc_api.SMSC()
		smsc.send_sms(self.client_phone, "Ваш код подтверждения: " + self.client_code_phone)

	def send_sms(self,text):
		print (text)
		smsc = smsc_api.SMSC()
		smsc.send_sms(self.client_phone, text)

	def send_mail(self,text):
		subject, from_email, to = 'Подтверждение регистрации', 'ruka2paka@yandex.ru', self.email
		text_content = 'This is an important message.'
		html_content =  text  
		msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

	def confirm_email(self, code):
		if code:
			if self.client_code_email == code:
				self.client_confirm_email = True
				self.client_code_email = ''
				self.save()
				return 0
			else:
				return 1
		else:
			return 1

	def confirm_phone(self, code):
		if code:
			if self.client_code_phone == code:
				self.client_confirm_phone = True
				self.client_code_phone = ""
				self.save()
				return 0
			else:
				return 1
		else:
			return 1

	def is_confirmed(self):
		if not self.client_confirm_phone or not self.client_confirm_email:
			return False
		else:
			return True

	def __str__(self):
		return (self.username + ": " + self.email + ": " + self.client_phone)

class Type_Work(models.Model):
	type_work = models.CharField(max_length=30, default=None)
	def __str__(self):
		return self.type_work
	class Meta:
		verbose_name = 'Вид приема'
		verbose_name_plural = 'Виды приемов'

class Timetable(models.Model):
	timetable_start = models.IntegerField(default=None)
	timetable_end = models.IntegerField(default=None)
	timetable_day_choice = (
        ('Monday', 'Понедельник'),
        ('Tuesday', 'Вторник'),
        ('Wednesday', 'Среда'),
        ('Thursday', 'Четверг'),
		('Friday', 'Пятница'),
		('Saturday', 'Суббота'),
		('Sunday', 'Воскресенье')
    )
	timetable_day = models.CharField(max_length=20,choices=timetable_day_choice,default=None)
	timetable_type = models.ForeignKey('Type_Work',default=None)
	timetable_expert = models.ForeignKey('expertroom.Expert',default=None)
	class Meta:
		verbose_name = 'Расписание'
		verbose_name_plural = 'Расписания'

class Appointment(models.Model):
	appointment_expert = models.ForeignKey('expertroom.Expert', blank=True)
	appointment_time = models.CharField(max_length=4, blank=True)
	appointment_date = models.DateField( blank=True)
	appointment_client = models.ForeignKey('Client', blank=True)
	appointment_type_work = models.ForeignKey('Type_Work', blank=True)
	appointment_description = models.ForeignKey('Appointment_Description', blank=True, null=True)
	appointment_answer = models.ForeignKey('Appointment_Answer', blank=True, null=True)
	NOT_CONFIRMED = 'NC'
	CONFIRMED = 'CF'
	CLOSED = 'CL'
	APPOINTMENT_STATUS_CHOICE = (
		(NOT_CONFIRMED, 'Не подтверждена'),
		(CONFIRMED, 'Подтверждена'),
		(CLOSED, 'Закрыта'),
	)
	appointment_status = models.CharField(max_length = 2, choices=APPOINTMENT_STATUS_CHOICE, default=NOT_CONFIRMED)

	def confirm(self):
		self.appointment_status = self.CONFIRMED
		self.send_info()

	def close(self):
		self.appointment_status = 'CL'

	def send_info(self):
		text = "Вы записаны " + str(self.appointment_date) + " на " + self.appointment_time + " к " + self.appointment_expert.expert_full_name()+". В " + self.appointment_expert.expert_filial.filial_organization.organization_name + " \""+ self.appointment_expert.expert_filial.filial_name+"\""
		smsc = smsc_api.SMSC()
		smsc.send_sms(self.appointment_client.client_phone, text)

	def set_date(self, date):
		self.appointment_date = datetime.datetime.strptime(date, "%Y-%m-%d").date()

	
	def appointment_client_username(self):
		return self.appointment_client.username

	def appointment_expert_type_work(self):
		return self.appointment_type_work.type_work

	def appointment_expert_first_name(self):
		return self.appointment_expert.first_name

	def appointment_expert_last_name(self):
		return self.appointment_expert.last_name

	def appointment_expert_organization(self):
		return self.appointment_expert.expert_filial.filial_organization.organization_name

	def appointment_expert_filial(self):
		return self.appointment_expert.expert_filial.filial_name

	class Meta:
		verbose_name = 'Запись на прием'
		verbose_name_plural = 'Записи на прием'

class Appointment_Description(models.Model):
	appointment_description_text = models.TextField(max_length=1000, default=None)
	appointment_description_img = models.ImageField(upload_to='img', blank=True, null=True, verbose_name='Фотография')

	class Meta:
		verbose_name = 'Запись на прием'
		verbose_name_plural = 'Записи на прием'

class Appointment_Answer(models.Model):
	appointment_desc = models.TextField(max_length=1000, default=None)
	appointment_ansver_img = models.ImageField(upload_to='img', blank=True, null=True, verbose_name='Фотография')

	class Meta:
		verbose_name = 'Запись на прием'
		verbose_name_plural = 'Записи на прием'

class FastPhone(models.Model):
	fast_phone = models.CharField(max_length=15, default="")
	fast_phone_code = models.CharField(max_length=5, default="")

	def set_code_phone(self):
		self.fast_phone_code = GS(5)
		self.save()
		return self.fast_phone_code

	def send_confirm_phone(self):
		print (self.set_code_phone())
		smsc = smsc_api.SMSC()
		smsc.send_sms(self.fast_phone, "Ваш код подтверждения: " + self.fast_phone_code)

	def confirm_phone(self, code):
		if self.fast_phone_code == code:
			return True
		else:
			return False

	def check_phone(cPhone):
		try:
			Client.objects.get(client_phone=cPhone)
			return False
		except:
			return True

templates/appointment.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="jumbotron">
				<h3>Ваша заявка на прием</h3>
				<hr>
				<h4>Организация: {{ appointment.appointment_expert.expert_organization() }}</h4>
				<h4>Отделение: {{ appointment.appointment_expert.expert_filial.filial_name }}</h4>
				<h4>Специалист: {{ appointment.appointment_expert.expert_full_name() }} </h4>
				<h4>Специальность: {{ appointment.appointment_expert.expert_speciality_name() }} </h4>
				<hr>
				<h4>Тип приема: {{ appointment.appointment_type_work.type_work }}</h4>
				<h4>Дата: {{ appointment.appointment_date }}</h4>
				<h4>Время: {{ appointment.appointment_time }}</h4>
				<hr>
				<h3>Описание:</h3>
				{% if appointment.appointment_description %}
					{% if appointment.appointment_description.appointment_description_text %}
					<p>
						{{ appointment.appointment_description.appointment_description_text }}
					</p>
					{% endif %}
					{% if appointment.appointment_description.appointment_description_img %}
						<img src="{{appointment.appointment_description.appointment_description_img.url}}" alt="" style="width: 200px; height: 200px;">
					{% endif %}
				{% else %}
					<h5><strong>Описания нет</strong></h5>
				{% endif %}
				{% if appointment.appointment_answer %}
					<br>
					<hr>
					<h3>Ответ врача</h3>
					{% if appointment.appointment_answer.appointment_desc %}
					<p>
						{{ appointment.appointment_answer.appointment_desc }}
					</p>
					{% endif %}
					{% if appointment.appointment_answer.appointment_ansver_img %}
						<img src="{{appointment.appointment_answer.appointment_ansver_img.url}}" alt="" style="width: 200px; height: 200px;">
					{% endif %}
				{% endif %}

			</div>				
		</div>
	</div>
</div>
{% endblock %}

templates/appointment_OR.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="jumbotron">
				<h3>Заявка</h3>
				<h3>{{appointment.get_appointment_status_display()}}</h3>
				<hr>
				<h4>Организация: {{ appointment.appointment_expert.expert_organization() }}</h4>
				<h4>Отделение: {{ appointment.appointment_expert.expert_filial.filial_name }}</h4>
				<div id="myTabContent" class="tab-content">
				  	<div class="tab-pane fade" id="EditForm">
						<form>
							{{ expert_form }}
							{{csrf_token | safe}}
							<input type="hidden" id="appointment_id" value="{{appointment.id}}">
						</form>
						<br>
						<a class="btn btn-primary" id="sendExpert" href="#Data"data-toggle="tab" aria-expanded="false"> Save </a>
					</div>
					<div class="tab-pane fade active in" id="Data">
						<h4 id="exp_name">Специалист: {{ appointment.appointment_expert.expert_full_name() }} </h4>
						<h4 id="exp_spec">Специальность: {{ appointment.appointment_expert.expert_speciality_name() }} </h4>
						<a href="#EditForm" data-toggle="tab" aria-expanded="true" >Изменить специалиста</a>
					</div>
				</div>
				
				<hr>
				<h4>Тип приема: {{ appointment.appointment_type_work.type_work }}</h4>
				<div id="myTabContent-1" class="tab-content">
				  	<div class="tab-pane fade" id="EditFormTime">
						<form>
							{{ date_time_form }}
							{{csrf_token | safe}}
							<input type="hidden" id="appointment_id" value="{{appointment.id}}">
						
						<br>
						<input class="btn btn-primary" type="button" id="sendTime" href="#Time"data-toggle="tab" aria-expanded="false" value="save"></input>

					</div>
					<div class="tab-pane fade active in" id="Time">
						<h4 id="app_date">Дата: {{ appointment.appointment_date }}</h4>
						<h4 id="app_time">Время: {{ appointment.appointment_time }}</h4>
						<h6 id="time_dng" class="text-danger"></h6>
						<h6 id="time_suc" class="text-success"></h6>
						<a href="#EditFormTime" data-toggle="tab" aria-expanded="true" >Изменить время</a>
					</div>
				</div>
				<hr>
				<h4> Клиент: {{appointment.appointment_client.full_name}} </h4>
				<h4> Телефон клиента: {{appointment.appointment_client.client_phone}} </h4>
				<h4> Еmail клиента: {{appointment.appointment_client.email}} </h4>
				<h3>Описание:</h3>
				{% if appointment.appointment_description %}
					{% if appointment.appointment_description.appointment_description_text %}
					<p>
						{{ appointment.appointment_description.appointment_description_text }}
					</p>
					{% endif %}
					{% if appointment.appointment_description.appointment_description_img %}
						<img src="{{appointment.appointment_description.appointment_description_img.url}}" alt="" style="width: 200px; height: 200px;">
					{% endif %}
				{% else %}
					<h5><strong>Описания нет</strong></h5>
				{% endif %}
				<div class="row">
					<div class="col-sm-3 col-sm-offset-3">
						<a href="{{url('operatorroom_AppointmentListView')}}" style="width: 100%" type='button' class='btn btn-default' >Отмена</a>
					</div>
					<div class="col-sm-3">
						<a href="{{urlGet('operatorroom_AppointmentListView',status='CL',id=appointment.id)}}" style="width: 100%" type='button' class='btn btn-danger' >Отклонить</a>
					</div>
					<div class="col-sm-3">
						<a href="{{urlGet('operatorroom_AppointmentListView',status='CF',id=appointment.id)}}" style="width: 100%" type='button' class='btn btn-success' >Подтвердить</a>
					</div>
						
					</div>
				</div>
			</div>				
		</div>
	</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% if title %}
		<title>{{title}}</title>
	{% else %}
		<title>НеТу ТайТлА!!!Аа!</title>
	{% endif %}
	
	<link rel="stylesheet" type="text/css" href="{{ static('css/bootstrap.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">		
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="{{ static('js/bootstrap.min.js') }}"></script>
	<script src="{{ static('js/jquery.redirect.js')}}"></script>
	<script type="text/javascript" src="{{ static('js/main.js') }}"></script>
</head>
<body>	
	{% include 'nav.html' %}
	{% include 'notification.html' %}
    {% block content %}{% endblock %}
</body>
</html>

templates/changepassword.html
{% extends "base.html" %}
{% block content %}

<div class="container">
	<div class="row">
			<div class="col-md-6">
			<div class="container_menu">
				</br>
				<form class="form-horizontal" action="" method="post">
					<h1 class="text-left col-sm-offset-4">Изменение номера телефона:</h1>
					<br>
					{% if error=='ErrorYourPhone'%}
					<br>
					<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
					<div class="alert alert-danger fade in">
					    <a href="#" class="close" data-dismiss="alert">&times;</a>
					    <strong>Вы указали ваш текущий номер телефона!</strong> Вы уже подттвердили данный номер телефона, на него будут приходить оповещения. Вы можете его поменять на другой, для этого укажите ваш новый номер в поле ниже.
					</div>
					</div>
					</div>
					{% endif %}
					<div class="form-group">
					{% for element in form %}
					<div class="form-group">
				   		<label for="element.id_for_label" class="col-sm-3 control-label">{{element.label}}</label>
					    <div class="col-sm-9">
					    {{element}}
				   		</div>
				   	</div>	
				   		{% endfor %}
				    </div>
				    {{ csrf_token|safe }}
				    <br>
					<div class="row">
					<div class="col-sm-3"></div>
					<div class="col-sm-6">
					<input type="submit" value="Изменить пароль" class="btn btn-lg btn-primary btn-block">
					</div>
				</form>
		</div>
	</div>
</div>
{% endblock %}

templates/codephoneconfirm.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
			<div class="col-md-6">
			<div class="container_menu">
				<br>
				<form class="form-horizontal" action="" method="post">
					<h1 class="text-left col-sm-offset-4 col-sm-8">Введите код подтверждения:</h1>
					<br>
					{% if error=='ErrorCode'%}
					<br>
					<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
					<div class="alert alert-danger fade in c">
					    <a href="#" class="close" data-dismiss="alert">&times;</a>
					    <strong>Указан неверный код!</strong> Код подтвердждения введен неверно, пожалуйста проверте смс сообщение и введите код еще раз.
					</div>
					</div>
					</div>
					{% endif %}
					{% if error=='ErrorPost'%}
					<br>
					<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
					<div class="alert alert-danger fade in c">
					    <a href="#" class="close" data-dismiss="alert">&times;</a>
					    <strong>Код указан в неверном формате!</strong> Код подтвердждения введен неверно. Пожалуйста проверте смс сообщение и введите код еще раз.
					</div>
					</div>
					</div>
					{% endif %}
					{% if error=='CodeResendet'%}
					<br>
					<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
					<div class="alert alert-info fade in c">
					    <a href="#" class="close" data-dismiss="alert">&times;</a>
					    <strong>Код подтверждения повторно отправлен</strong>
					</div>
					</div>
					</div>
					{% endif %}
					<div class="form-group">
				   		<label for="element.id_for_label" class="col-sm-4 control-label">{{form.confirm_code_phone_form_code.label}}</label>
					    <div class="col-sm-8">
					    {{form.confirm_code_phone_form_code}}
					    <p><a href="{{ urlGet('timetable_edit_confirmcodephone',code='resend')}}"> Отправить код еще раз</a></p>
						
				   		</div>

				    </div>
				    <div class="form-group", style="margin-top: -25px">
				   		<label for="element.id_for_label" class="col-sm-4 control-label">
				   		</label>
					    <div class="col-sm-8">
					    <h5>Код подтверждения отправлен на номер +{{phone}}</h6>
					    <p style="margin-top: -10px"><a href="{{ url('timetable_edit_confirmphone')}}"> Изменить номер телефона</a></p> 
				   		</div>
				    </div>
				    {{ csrf_token|safe }}
					<div class="row">
					<div class="col-sm-4"></div>
					<div class="col-sm-6">
					<input type="submit" value="Подтвердить код" class="btn btn-lg btn-primary btn-block">
					</div>
				</form>
		</div>
	</div>
</div>
{% endblock %}

templates/exp_index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="row">
				<div class="col-md-6 col-md-offset-1">
					<h3 class="text-center">{{ expert.first_name }} {{ expert.last_name }} {{ expert.expert_patronymic }}</h3>
					<p>{{ expert.expert_description }}</p>
				</div>
				<div class="col-md-4">
					<img src="{{ expert.expert_image.url }}" class="img-rounded" style="width: 160px; height: 300px; display:block; margin:0 auto;">		
				</div>

			</div>
			<br><br>
			<hr>
			<br><br>
			<h2 class="text-center">Расписание</h2>
			<ul class="nav nav-tabs">
				{% for x in timetablelist %}
					<li class="{% if loop.index == 1 %}active{% endif %}">
						<a href="#{{ loop.index }}" data-toggle="tab" aria-expanded="{% if loop.index == 1 %}false{% else %}true{% endif %}">
							{{ x['date'] }}
						</a>
					</li>
				{% endfor %}
			</ul>
			<div id="myTabContent" class="tab-content" style="min-height:200px;">

				{% for table in timetablelist %}
					<div class="tab-pane fade {% if loop.index == 1 %}active in{% endif %}" id="{{ loop.index }}">
						{% if not table['rasp'] %}
							<h2 class="text-center"> Нет записей </h2>
						{% else %}
							<table class="table table-striped table-hover">
								<thead>
									<tr>
										<th>Тип приема</th>
										<th colspan="3" class="text-center">Время</th>
									</tr>
								</thead>
								<tbody>
									{% for x in table['rasp'] %}
									{% set rowloop = loop %}
										<tr class="" id="tr_{{loop.index}}_{{table['date']}}">
											<td>{{ x['name'] }}</td>
											{% for j in x['time'] %}
												<td>
													<div class="checkbox">
				  										<label><input id="cell_{{rowloop.index}}/{{rowloop.revindex}}_{{loop.index}}/{{loop.revindex}}_{{table['date']}}" type="checkbox" class="chb" date="{{ table['date'] }}" time="{{ j }}" table_type="{{ x['table_type_id'] }}">{{ j }}</label>
				  									</div>
												</td>
											{% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							</table> 
						{% endif %}
					</div>
				{% endfor %}
				<form action="" method="POST">
					{{ csrf_token | safe }}
					<input type="hidden" id="expert_id" value="{{ expert.id }}">
					<input class="btn btn-default" id="submitbtn" type="button" value="Оставить заявку" />
				</form>
			</div>
			


			
		</div>
	</div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<div class="container_menu">
				<form class="form-horizontal" action="" method="post">
					<h1 class="text-center">Войти: </h1><br>

					{% if result  %}
					<br>
					<div class="alert alert-dismissible alert-danger">
						<button type="button" class="close" data-dismiss="alert">×</button>
						{% if result == 1 %}
							<strong>Ошибка при вводе логина и пароля!</strong> Проверьте введеные данные.
						{% elif result == 2 %}
							<strong>Аккаунт не активен!</strong> Обратитесь к администратору.
						{% endif %}
					</div>
					{% endif %}

					{{ csrf_token|safe }}

					{{ form.login_form_username.errors }}
					<label for="{{ form.login_form_username.id_for_label }}">Введите ваш логин:</label>
					{{ form.login_form_username }}

					<br>
					
					{{ form.login_form_password.errors }}
					<label for="{{ form.login_form_password.id_for_label }}">Введите ваш пароль:</label>
					{{ form.login_form_password }}

					<br>
					
					<input type="submit" value="Войти" class="btn btn-lg btn-primary btn-block">
				</form>
				<br>	<br>
			</div>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>
{% endblock %}

templates/nav.html
<!-- Navigation menu -->
 <nav class="navbar navbar-default">
  <div class="container container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url('timetable_root')}}">Medical base</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated() %}
        {% if getUserType(user)=="Client" %}      
		    <li class="active"><a href="{{ url('timetable_organizations') }}"> Организации <span class="sr-only"></span></a></li>
      	<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Профиль<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url('timetable_edit')}}">Редактировать профиль</a></li>
              <li><a href="{{ url('appointment_list')}}">Мои заявки</a></li>
              <li class="divider"></li>
              <li><a href="{{ url('timetable_login') }}?logout=true">Выйти</a></li>
            </ul>
        </li>
        {% elif getUserType(user)=="Operator" %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Профиль<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url('timetable_login') }}?logout=true">Выйти</a></li>
            </ul>
          </li>
        {% elif getUserType(user)=="Expert" %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Профиль<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url('timetable_login') }}?logout=true">Выйти</a></li>
            </ul>
          </li>
        {% endif %}
      {% else %}        
        <li><a href="{{ url('timetable_organizations') }}"> Организации <span class="sr-only"></span></a></li>
        <li><a href="{{ url('timetable_registration') }}">Регистрация</a></li>
        <li><a href="{{ url('timetable_login') }}">Войти<span class="sr-only"></span></a></li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- End navigation menu -->

templates/or_index.html
{% extends "base.html" %}
{% block content %}
	
{% endblock %}